Added --bind_ip 127.0.0.1 option when the mongod service started.

diff --git a/etc/init.d/mongodb b/etc/init.d/mongodb
--- a/etc/init.d/mongodb
+++ b/etc/init.d/mongodb
@@ -67,6 +67,7 @@ PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/mongo/bin
 DAEMON=/opt/mongo/bin/mongod
 LOGDIR=/opt/mongo/log
 DATA=/opt/mongo/data
+IP=127.0.0.1
 NAME=mongodb
 DESC=database
 
@@ -88,12 +89,12 @@ DIETIME=10                  # Time to wait for the server to die, in seconds
                             # 'restart' will not work
 
 LOGFILE=$LOGDIR/$NAME.log  # Server logfile
-DAEMON_OPTS="--dbpath $DATA --logpath $LOGFILE run"
+DAEMON_OPTS="--dbpath $DATA --logpath $LOGFILE --bind_ip $IP run"
 
 
 # Include mongodb defaults if available
 if [ -f /etc/default/$NAME ] ; then
-	. /etc/default/$NAME
+    . /etc/default/$NAME
 fi
 
 DAEMONUSER=mongodb
@@ -149,7 +150,7 @@ start_server() {
                         --exec $DAEMON -- $DAEMON_OPTS
             errcode=$?
         fi
-	return $errcode
+    return $errcode
 }
 
 stop_server() {
@@ -166,7 +167,7 @@ stop_server() {
             errcode=$?
         fi
 
-	return $errcode
+    return $errcode
 }
 
 reload_server() {
@@ -179,27 +180,27 @@ reload_server() {
 
 force_stop() {
 # Force the process to die killing it manually
-	[ ! -e "$PIDFILE" ] && return
-	if running ; then
-		kill -15 $pid
-	# Is it really dead?
-		sleep "$DIETIME"s
-		if running ; then
-			kill -9 $pid
-			sleep "$DIETIME"s
-			if running ; then
-				echo "Cannot kill $NAME (pid=$pid)!"
-				exit 1
-			fi
-		fi
-	fi
-	rm -f $PIDFILE
+    [ ! -e "$PIDFILE" ] && return
+    if running ; then
+        kill -15 $pid
+    # Is it really dead?
+        sleep "$DIETIME"s
+        if running ; then
+            kill -9 $pid
+            sleep "$DIETIME"s
+            if running ; then
+                echo "Cannot kill $NAME (pid=$pid)!"
+                exit 1
+            fi
+        fi
+    fi
+    rm -f $PIDFILE
 }
 
 
 case "$1" in
   start)
-	log_daemon_msg "Starting $DESC $NAME"
+    log_daemon_msg "Starting $DESC $NAME"
         # Check if it's running first
         if running ;  then
             log_progress_msg "apparently already running"
@@ -227,7 +228,7 @@ case "$1" in
         log_daemon_msg "Stopping $DESC" "$NAME"
         if running ; then
             # Only stop the server if we see it running
-			errcode=0
+            errcode=0
             stop_server || errcode=$?
             log_end_msg $errcode
         else
@@ -243,14 +244,14 @@ case "$1" in
         if running; then
             # If it's still running try to kill it more forcefully
             log_daemon_msg "Stopping (force) $DESC" "$NAME"
-			errcode=0
+            errcode=0
             force_stop || errcode=$?
             log_end_msg $errcode
         fi
         ;;
   restart|force-reload)
         log_daemon_msg "Restarting $DESC" "$NAME"
-		errcode=0
+        errcode=0
         stop_server || errcode=$?
         # Wait some sensible amount, some server need this
         [ -n "$DIETIME" ] && sleep $DIETIME
@@ -278,10 +279,10 @@ case "$1" in
         ;;
   # And this if it cann
   *)
-	N=/etc/init.d/$NAME
-	echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
-	exit 1
-	;;
+    N=/etc/init.d/$NAME
+    echo "Usage: $N {start|stop|force-stop|restart|force-reload|status}" >&2
+    exit 1
+    ;;
 esac
 
 exit 0
